server {
    listen 80;
    listen [::]:80;
    server_name  api.athl.athl-logistique.com;

    # Porte que Let's Encrypt utilise pour vérifier qu'on contrôle bien ce domaine (et pour le renouvellement).
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  api.athl.athl-logistique.com;

    ssl_certificate     /etc/letsencrypt/live/athl-logistique.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/athl-logistique.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        proxy_set_header Host $host;
        proxy_pass   http://athl_back:8080;
    }
}
