server {
    server_name  api.athl.athl-logistique.com;

    # Porte que Let's Encrypt utilise pour vérifier qu'on contrôle bien ce domaine.
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass   http://athl_back:8080;
    }

}