server {
    server_name  athl.athl-logistique.com;

    location / {
        proxy_set_header Host $host;
        proxy_pass   http://athl-front;
    }

    location /imc {
        proxy_set_header Host $host;
        proxy_pass   http://athl_back:8080;
    }
    
}